services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}

  frontend:
    build:
      context: ..\..\meeting-summarizer-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:80"
    depends_on:
      - backend
