services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}

      # ✅ Spring-friendly names (these map to spring.mail.*)
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}

      # your custom prop for @Value("${mail.from}")
      MAIL_FROM: ${MAIL_FROM}

  frontend:
    build:
      # ✅ Use forward slashes; Railway/Linux runners may choke on backslashes
      context: ../../meeting-summarizer-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:80"
    depends_on:
      - backend
